version: "3.9"

services:
  ratelimiter-api:
    build:
      context: .
    image: ratelimiter-api:latest
    container_name: ratelimiter-api
    ports:
      - "8080:8080"
    environment:
      # Optional JVM tuning (adjust as you like)
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75
      # Optional Spring profile (leave unset to use defaults)
      # - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/actuator/health"] # if actuator is enabled
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 20s
    restart: unless-stopped
