services:
  ratelimiter-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7.4

  tests:
    image: maven:3.9.9-eclipse-temurin-21
    working_dir: /app
    volumes:
      - .:/app
    command: mvn test
