ratelimiter:
  clients:
    - id: "xyz"
      limit: 500
    - id: "abc"
      limit: 200
    - id: "free"
      limit: 3
    - id: "premiumUser"
      limit: 2000
  performance:
    window-seconds: 60
    flush-interval-ms: 100
    shard-count: 10

management:
  endpoints:
    web:
      exposure:
        include: health
